Repository legend-exp/dspeed, pull requests merged in 2024-01, with the labels that each got.

#37 Support the latest legend-pydataobj version
  docs/source/notebooks/DSPTutorial.ipynb
  docs/source/notebooks/IntroToDSP.ipynb
  docs/source/notebooks/WaveformBrowser.ipynb
  setup.cfg
  src/dspeed/build_dsp.py
  src/dspeed/processing_chain.py
  src/dspeed/processors/wiener_filter.py
  src/dspeed/vis/waveform_browser.py
  tests/conftest.py
  tests/processors/test_histogram.py
  tests/test_build_dsp.py
  tests/test_list_parsing.py
  tests/test_numpy_constants_parsing.py
Labels: dependencies

#39 Add missing SciPy dependency to `setup.cfg`
  setup.cfg
  tests/processors/test_import.py
Labels: bug, dependencies

#44 Added ability to set LGDO attributes through `build_dsp()`
  src/dspeed/build_dsp.py
  src/dspeed/processing_chain.py
  src/dspeed/vis/waveform_browser.py
  tests/processors/test_histogram.py
  tests/test_list_parsing.py
  tests/test_numpy_constants_parsing.py
  tests/test_processing_chain.py
Labels: enhancement
